server:
  port: ${port}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${git}
          username: ${username}
          password: ${password}
          clone-on-start: true
          skip-ssl-validation: true
          timeout: 10
    label: main
eureka:
  client:
    service-url:
      defaultZone: ${eureka}