version: '3'
services:
  app:
    restart: always
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      - ${port}:${port}
    environment:
      eurekaUser: ${eurekaUser}
      eurekaPassword: ${eurekaPassword}
      eurekaUrl: ${eurekaUrl}
      eurekaPort: ${eurekaPort}
      port: ${port}
      host: ${host}
    command: mvn clean spring-boot:run