version: '3'
services:
  redis:
    container_name: shuttle-redis
    image: redis
    command: redis-server --requirepass ${redisPassword}
    ports:
      - 6379:6379
  app:
    restart: always
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      - ${port}:${port}
    environment:
      redisHost: redis
      redisPassword: ${redisPassword}
      eurekaUser: ${eurekaUser}
      eurekaPassword: ${eurekaPassword}
      eurekaUrl: ${eurekaUrl}
      eurekaPort: ${eurekaPort}
      port: ${port}
      host: ${host}
    command: mvn clean spring-boot:run
    depends_on:
      - redis