version: '3'
services:
  app:
    restart: always
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      - ${port}:${port}
    environment:
      user: ${user}
      password: ${password}
      port: ${port}
    command: mvn clean spring-boot:run