server:
  port: ${port}
spring:
  application:
    name: ${name}
  security:
    user:
      name: ${user}
      password: ${password}
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false