version: '3'
services:
  app:
    restart: always
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
    environment:
      configLabel: ${configLabel}
      configUrl: ${configUrl}
      configName: ${configName}
      configSecurityName: ${configSecurityName}
      configSecurityPassword: ${configSecurityPassword}
    command: mvn clean spring-boot:run