server:
  port: ${port}
spring:
  application:
    name: ${name}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${user}:${password}@${eureka-url}:${eureka-port}/eureka/

feign:
  hystrix:
    enabled: true
jwt:
  key: ${key}