server:
  port: 8002
spring:
  application:
    name: feign
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://shuttle:shuttle@localhost:8001/eureka/

feign:
  hystrix:
    enabled: true