server:
  port: ${port}8002
spring:
  application:
    name: ${name}feign
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${user}:${password}@${eureka-url}:${eureka-port}/eureka/

feign:
  hystrix:
    enabled: true