server:
  port: ${port}
spring:
  application:
    name: ${name}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${user}:${password}@${eureka-url}:${eureka-port}/eureka/

feign:
  hystrix:
    enabled: true
  httpclient:
    # feign最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
    okhttp:
      # 让feign使用Apache okhttp做请求，而不是默认的urlConnection
      enabled: true
jwt:
  key: ${key}